(let ((q 'q))
  (let ((w 'w) (s 's))
    (let ((e 'e) (d 'd) (c 'c))
      (let ((r 'r))
        (let ((t 't) (g 'g) (b 'b) (y 'y) (h 'h) (n 'n))
          (let ((u 'u))
            `((q ,q) (w ,w) (s ,s) (e ,e) (d ,d) (c ,c) (r ,r) (t ,t) (g ,g) (b ,b) (y ,y) (h ,h) (n ,n) (u ,u))))))))